data_type: raw
dataloader_args:
  drop_last: true
  num_workers: 8
  pin_memory: false
  prefetch_factor: 8
dataset_args:
  aug_prob: 0.6
  fbank_args:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  num_frms: 200
  num_spk: 128
  num_utts_per_spk: 2
  resample_rate: 16000
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  spec_aug: false
  spec_aug_args:
    max_f: 8
    max_t: 10
    num_f_mask: 1
    num_t_mask: 1
    prob: 0.6
  speed_perturb: false
exp_dir: /hpctmp/ma_yi/exp/2pooling_cstrPho0.0007_HardDiff.00001_selfcstr0.003
gpus:
- 0
log_batch_interval: 100
loss: CrossEntropyLoss
loss_args: {}
margin_scheduler: MarginScheduler
margin_update:
  epoch_iter: 580
  final_margin: 0.2
  fix_start_epoch: 3640
  increase_start_epoch: 1820
  increase_type: exp
  initial_margin: 0.0
  update_margin: true
model: ECAPA_TDNN_c512
model_args:
  embed_dim: 192
  feat_dim: 80
  pooling_func: TSTP
model_init: null
noise_data: /scratch/ma_yi/dataset_vox1/musan/file_list
num_avg: 10
num_epochs: 13650
optimizer: SGD
optimizer_args:
  lr: 0.1
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001
pho_path: /scratch/ma_yi/dataset_vox1/voxceleb1/wav
projection_args:
  easy_margin: false
  embed_dim: 192
  num_class: 1211
  project_type: arc_margin
  scale: 32.0
reverb_data: /scratch/ma_yi/dataset_vox1/RIRS_NOISES/file_list
save_epoch_interval: 1000
scheduler: ExponentialDecrease
scheduler_args:
  epoch_iter: 580
  final_lr: 5.0e-05
  initial_lr: 0.1
  num_epochs: 13650
  scale_ratio: 4.0
  warm_from_zero: true
  warm_up_epoch: 6
seed: 42
train_data: data/vox1_training/raw.list
train_label: data/vox1_training/utt2spk
weight_cstr: 0.0007
weight_diff: 1.0e-05
weight_selfcstr: 0.003
